////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at
  http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

:page-pagination:

= Asynchronous Web Service

== Description

This web service variant is used to execute long-running workflows.

== Related Plugins

The following servlet plugins are used to run and query the status of a workflow asynchronously:

* Run a workflow: `asyncRun?service=<name>&<parameter>=<value>&<variable>=<value>`
* Get the status: `asyncStatus?service=<name>`

== Options

[options="header"]
|===
|Option |Description
|Name|The name of the asynchronous web service.  This is the name that is passed into the `asyncRun` webService URL.
|Enabled|Enables or disabled this Asynchronous Web Service
|Filename on the server|This is the filename on the server.  Make sure that the workflow you want to execute is available on the server.
|Content type|The content type which will get reported by the webService servlet
|List status on server|Enable this option if you want the executions of the asynchronous web service workflow(s) to be listed in the status of the server.
|===

== Samples

None